import Head from 'next/head'
import Image from 'next/image'
import { Inter, Patrick_Hand } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })


const patrickHand = Patrick_Hand({
    weight: '400',
    subsets: ['latin'],
  })


export default function Home() {
  return (
    <>
      <Head>
        <title>Hallows Eve</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>
      <main className={styles.bg}>
        <section>
            <div className='container' style={{textAlign:"center"}}>
                <div className='wrapper'>
                <h1 className={[patrickHand.className, 'logo'].join(" ")}>HALLOWS EVE</h1>
                <a className={[styles.fancyBtn, "my-5",inter.className].join(" ")} >START</a>
                <p className={[inter.className,'fs-caption'].join(" ")}>THE DARK DESCENT INTO GOOGLE TRENDS MOST POPULAR COSTUMES. 2022</p>
                </div>
                
            </div>
        </section>
        <div className='overlay'></div>
      </main>
    </>
  )
}
